server:
  port: 8000
  servlet:
    context-path: /erp-base-goods-service

spring:
  application:
    name: erp-base-goods-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/goods?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: 930310
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 15
      max-wait: 5000
      time-between-eviction-runs-millis: 90000
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

mybatis:
  # model的包
  type-aliases-package: com.brave.erp.base.goods.service.mapper
  mapper-locations: "classpath:mapper/**/*.xml"
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# redis
redisson:
  address: redis://127.0.0.1:6379
  timeout: 1000
  database: 0

# nacos + dubbo
dubbo:
  application: #当前这个应用的信息
    name: erp-base-goods-service
    version: 1.0.1
    owner: brave
    organization: ERP
    environment: product
#    logger: slf4j
  #    register-mode: instance
  protocol: # 服务采用的协议 基本默认未dubbo协议(netty)
    name: dubbo
    port: 20884 #dubbo服务暴露的端口
#    accesslog: true
  registry: #注册相关信息
    address: nacos://127.0.0.1:8848 #注册中心配置
    timeout: 30000 # 到注册中心的超时时间
#    parameters:
#      namespace: defe3773-7dc7-4b14-9bb1-da3ccfea77da
  provider:
    retries: -1 #重试次数 consumer
    delay: -1 #延迟到spring容器加载之后
#    validation: jvalidatorNew
  consumer:
    # 服务连接超时时间
    timeout: 3000
    # 取消服务启动检查
    check: false
    layer: service
    owner: brave
  monitor:
    protocol: registry
  config-center:
    protocol: nacos
    address: nacos://127.0.0.1:8848
  metadata-report:
    address: nacos://127.0.0.1:8848
    protocol: nacos
    username: nacos
    password: nacos



